#!/usr/bin/env python3
"""Build a static analysis website from the corpus survey artifacts.

Reads:
  corpus/survey.json            -- in-Python static survey
  corpus/elflint_summary.json   -- eu-elflint oracle aggregation
  corpus/dep_graph.json         -- DT_NEEDED graph analysis (optional)

Writes:
  docs/index.html               -- dashboard
  docs/{header,program,dynamic,relocations,symbols,notes,
        hardening,categories,anomalies,elflint,packages,needed,
        depgraph}.html
  docs/style.css                -- minimal styling
  docs/data.json                -- raw combined data (for drill-downs)

The site is plain HTML + a tiny vanilla-JS Chart.js setup. No build
step needed; open `docs/index.html` in a browser or serve with
`python -m http.server`.

The output dir is named `docs/` so GitHub Pages can serve it
directly from the `main` branch with no extra config.
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SURVEY = ROOT / "corpus" / "survey.json"
ELFLINT = ROOT / "corpus" / "elflint_summary.json"
DEPGRAPH = ROOT / "corpus" / "dep_graph.json"
SITE = ROOT / "docs"

CHART_CDN = (
    '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/'
    'dist/chart.umd.min.js"></script>'
)

NAV = [
    ("index.html",       "Dashboard"),
    ("categories.html",  "Categories"),
    ("header.html",      "ELF Header"),
    ("program.html",     "Program Headers"),
    ("dynamic.html",     "Dynamic"),
    ("relocations.html", "Relocations"),
    ("symbols.html",     "Symbols"),
    ("notes.html",       "Notes & Props"),
    ("hardening.html",   "Hardening"),
    ("packages.html",    "Packages"),
    ("needed.html",      "NEEDED graph"),
    ("depgraph.html",    "Dep graph"),
    ("anomalies.html",   "Survey anomalies"),
    ("elflint.html",     "elflint findings"),
]


# ---------- helpers ----------------------------------------------------------


def _esc(s: object) -> str:
    return html.escape(str(s))


def _fmt(n: int) -> str:
    return f"{n:,}"


def page(title: str, here: str, body: str, *, byline: str = "") -> str:
    nav_html = " · ".join(
        f'<a class="{"active" if href == here else ""}" '
        f'href="{href}">{_esc(label)}</a>'
        for href, label in NAV
    )
    bline = (f'<p class="byline">{byline}</p>'
             if byline else "")
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)} — ElfZoo corpus</title>
<link rel="stylesheet" href="style.css">
{CHART_CDN}
</head>
<body>
<header>
  <h1><a href="index.html">ElfZoo</a> — {_esc(title)}</h1>
  <nav>{nav_html}</nav>
  {bline}
</header>
<main>
{body}
</main>
<footer>
  <p>Generated by <code>scripts/build_site.py</code> from
     <code>corpus/survey.json</code>,
     <code>corpus/elflint_summary.json</code>, and
     <code>corpus/dep_graph.json</code>.
     Raw data: <a href="data.json">data.json</a>.</p>
</footer>
</body>
</html>
"""


def section(title: str, body: str, *, anchor: str | None = None) -> str:
    a = f' id="{_esc(anchor)}"' if anchor else ""
    return f'<section{a}><h2>{_esc(title)}</h2>\n{body}\n</section>\n'


def kv_card(label: str, value: str, sub: str = "") -> str:
    s = f'<div class="sub">{_esc(sub)}</div>' if sub else ""
    return (
        f'<div class="card">'
        f'<div class="num">{_esc(value)}</div>'
        f'<div class="lbl">{_esc(label)}</div>'
        f'{s}'
        f'</div>'
    )


def card_grid(cards: list[str]) -> str:
    return '<div class="grid">' + "\n".join(cards) + "</div>"


def table(headers: list[str], rows: list[list[str]],
          *, sortable: bool = True, klass: str = "data") -> str:
    cls = klass + (" sortable" if sortable else "")
    h = "".join(f"<th>{_esc(x)}</th>" for x in headers)
    r = "\n".join(
        "<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>"
        for row in rows
    )
    return (
        f'<table class="{cls}"><thead><tr>{h}</tr></thead>'
        f'<tbody>{r}</tbody></table>'
    )


def kv_table(d: dict, *, key_label: str = "value",
             val_label: str = "count", limit: int | None = None,
             total: int | None = None) -> str:
    items = sorted(d.items(), key=lambda kv: -_n(kv[1]))
    if limit is not None:
        items = items[:limit]
    if total is None:
        total = sum(_n(v) for v in d.values())
    rows = []
    for k, v in items:
        n = _n(v)
        pct = (n / total * 100) if total else 0.0
        rows.append([_esc(k), _fmt(n), f"{pct:.2f}%"])
    return table([key_label, val_label, "share"], rows)


def _n(v) -> int:
    if isinstance(v, dict) and "count" in v:
        return int(v["count"])
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def chart_bar(canvas_id: str, labels: list[str],
              data: list[int], title: str = "",
              *, horizontal: bool = False,
              height: int = 280) -> str:
    cfg = {
        "type": "bar",
        "data": {
            "labels": labels,
            "datasets": [{
                "label": title,
                "data": data,
                "backgroundColor": "#3b6ea5",
                "borderRadius": 2,
            }],
        },
        "options": {
            "indexAxis": "y" if horizontal else "x",
            "responsive": True,
            "maintainAspectRatio": False,
            "plugins": {
                "legend": {"display": False},
                "title": {"display": bool(title), "text": title},
            },
            "scales": {"x": {"ticks": {"autoSkip": True}}},
        },
    }
    return (
        f'<div class="chart" style="height:{height}px">'
        f'<canvas id="{canvas_id}"></canvas></div>'
        f'<script>new Chart('
        f'document.getElementById({json.dumps(canvas_id)}),'
        f'{json.dumps(cfg)});</script>'
    )


def chart_pie(canvas_id: str, labels: list[str], data: list[int],
              title: str = "", *, height: int = 280) -> str:
    cfg = {
        "type": "doughnut",
        "data": {
            "labels": labels,
            "datasets": [{
                "data": data,
                "backgroundColor": [
                    "#3b6ea5", "#e07b3a", "#5d9b6c", "#a85a8e",
                    "#7a7a7a", "#c9b237", "#5a8fb3", "#b35a5a",
                    "#7d6ea0", "#56a39a", "#a39a56", "#9a56a3",
                ],
            }],
        },
        "options": {
            "responsive": True,
            "maintainAspectRatio": False,
            "plugins": {
                "legend": {"position": "right"},
                "title": {"display": bool(title), "text": title},
            },
        },
    }
    return (
        f'<div class="chart" style="height:{height}px">'
        f'<canvas id="{canvas_id}"></canvas></div>'
        f'<script>new Chart('
        f'document.getElementById({json.dumps(canvas_id)}),'
        f'{json.dumps(cfg)});</script>'
    )


def top_n(d: dict, n: int = 20) -> tuple[list[str], list[int]]:
    items = sorted(d.items(), key=lambda kv: -_n(kv[1]))[:n]
    return [str(k) for k, _ in items], [_n(v) for _, v in items]


def sample_list(samples: list[str], *, max_n: int = 10) -> str:
    if not samples:
        return "<em>(none)</em>"
    items = "".join(
        f"<li><code>{_esc(s)}</code></li>"
        for s in samples[:max_n]
    )
    extra = (
        f"<li><em>… and {len(samples) - max_n:,} more</em></li>"
        if len(samples) > max_n else ""
    )
    return f"<ul class='paths'>{items}{extra}</ul>"


def details(summary: str, body: str) -> str:
    return (
        f'<details><summary>{_esc(summary)}</summary>{body}</details>'
    )


# ---------- per-page builders -----------------------------------------------


def build_dashboard(survey: dict, el: dict, sv: dict) -> str:
    """The dashboard reports the **whole corpus** totals (sv["all"])
    plus a categories breakdown. Other pages drill into the loadable
    bucket, since that's the actual loader-spec target."""
    n = survey["n_files"]
    machines = sv["machine"]
    classes = sv["class"]
    cats = survey["category_counts"]
    loadable_n = survey["by_category"]["loadable"]["n_files"]
    cards = [
        kv_card("ELFs", _fmt(n), "across main + community"),
        kv_card("loadable", _fmt(loadable_n),
                f"{loadable_n/n*100:.1f}% — loader-spec target"),
        kv_card("packages", _fmt(len(sv["pkg_n_files"])),
                "unique <pkg-ver-rel> dirs"),
        kv_card("clean (elflint)", _fmt(el["n_clean"]),
                f'{el["n_clean"]/el["n_files"]*100:.1f}% of corpus'),
        kv_card("dirty (elflint)", _fmt(el["n_dirty"]),
                f'{el["n_dirty"]/el["n_files"]*100:.1f}% of corpus'),
        kv_card("elflint findings", _fmt(el["n_total_findings"]),
                f'{el["n_distinct_kinds"]} distinct kinds'),
        kv_card("survey anomalies", _fmt(sum(sv["anomalies"].values())),
                f'{len(sv["anomalies"])} kinds (all files)'),
        kv_card("relocation types", _fmt(len(sv["reloc_types"])),
                f'{len(sv["reloc_types_per_arch"])} architectures'),
        kv_card("NEEDED libraries", _fmt(len(sv["needed_libs"])),
                "distinct DT_NEEDED targets"),
        kv_card("PT_INTERP variants", _fmt(len(sv["interps"])),
                "distinct loader paths"),
        kv_card("BIND_NOW", _fmt(sv["files_with_bind_now"]),
                f'{sv["files_with_bind_now"]/max(1,sv["n_files"])*100:.1f}% '
                f'of all-files are full-RELRO'),
    ]

    clabels, cvals = zip(*sorted(cats.items(), key=lambda kv: -kv[1])) \
        if cats else ([], [])
    et = sv["elf_type"]
    etl, etv = zip(*sorted(et.items(), key=lambda kv: -kv[1])) \
        if et else ([], [])
    return (
        section("Corpus at a glance", card_grid(cards))
        + section("Categories",
                  chart_pie("ch_cats", list(clabels), list(cvals),
                            "ELFs per category")
                  + table(["category", "ELFs", "share"],
                          [[_esc(k), _fmt(v), f"{v/n*100:.2f}%"]
                           for k, v in sorted(cats.items(),
                                              key=lambda kv: -kv[1])])
                  + "<p>See the <a href='categories.html'>Categories</a> "
                  "page for full per-bucket detail. All other pages "
                  "show data from the <strong>loadable</strong> "
                  "bucket only — the real loader-spec target.</p>")
        + section("Loadable e_type",
                  "<p>The loadable bucket is by construction "
                  "<code>EM_X86_64</code> + <code>ELFCLASS64</code> + "
                  "<code>ELFDATA2LSB</code>. The only remaining "
                  "ELF-header axis with variety here is the file "
                  "type: shared objects vs executables. The "
                  "<a href='header.html'>ELF Header</a> page shows "
                  "the full corpus's variety on every axis.</p>"
                  + chart_pie("ch_et", list(etl), list(etv),
                              "ET_ distribution (loadable)"))
        + section("How to read this site", """
<p>This corpus is every <code>.apk</code> in Alpine
<strong>main + community / x86_64</strong>, unpacked and indexed by
<code>llvm-readobj-20 --elf-output-style=JSON</code>. Two parallel
static-analysis passes feed the site:</p>
<ul>
<li><strong>Survey</strong> (<code>scripts/survey.py</code>) — fast
    in-Python parser of the JSON dumps. Counts every ELF field,
    cross-references against the spec, classifies each file into
    one of five categories (loadable / debuginfo / relocatable /
    cross_arch / other) and emits structured anomalies (e.g.
    <code>ph_load_wx</code> when a PT_LOAD is W+X).</li>
<li><strong>eu-elflint oracle</strong>
    (<code>scripts/elflint_run.py</code>) — wraps elfutils 0.190
    <code>eu-elflint -q</code> over the same corpus, normalises each
    finding into a message template, and buckets by template.
    Independent second opinion: we agree on what's broken when both
    fire.</li>
</ul>
<p>Use the nav to drill into any axis. The
<a href="anomalies.html">anomalies</a> and
<a href="elflint.html">elflint</a> pages are the two strongest
signals about non-standard ELFs in this corpus.</p>
""")
    )


def build_header(sv: dict) -> str:
    machines = sv["machine"]
    mlabels, mvals = top_n(machines, 25)
    return (
        section("Machine (e_machine) — full distribution",
                chart_bar("h_mach_full", mlabels, mvals,
                          "ELFs per e_machine (top 25)",
                          height=420)
                + kv_table(machines, key_label="e_machine"))
        + section("ELF class (e_ident[EI_CLASS])",
                  chart_pie("h_cls", *top_n(sv["class"]))
                  + kv_table(sv["class"], key_label="ELFCLASS"))
        + section("Data encoding (e_ident[EI_DATA])",
                  chart_pie("h_data", *top_n(sv["data_encoding"]))
                  + kv_table(sv["data_encoding"], key_label="ELFDATA"))
        + section("OS/ABI (e_ident[EI_OSABI])",
                  chart_pie("h_osabi", *top_n(sv["osabi"]))
                  + kv_table(sv["osabi"], key_label="ELFOSABI"))
        + section("File type (e_type)",
                  chart_pie("h_etype", *top_n(sv["elf_type"]))
                  + kv_table(sv["elf_type"], key_label="ET_"))
        + section("Loader (PT_INTERP)",
                  kv_table(sv["interps"], key_label="PT_INTERP"))
    )


def build_program(sv: dict) -> str:
    ph = sv["phdr_types"]
    perms = sv["phdr_perm_combos"]
    seg = {str(k): v for k, v in sv["segment_count_histogram"].items()}
    ptload = {str(k): v for k, v in sv["pt_load_count_histogram"].items()}
    return (
        section("Program header types (PT_*)",
                chart_bar("p_types", *top_n(ph, 15),
                          title="ELFs containing each PT_*",
                          height=320)
                + kv_table(ph, key_label="PT_type"))
        + section("PT_LOAD permission combinations",
                  chart_pie("p_perms", *top_n(perms))
                  + kv_table(perms, key_label="permissions"))
        + section("PT_LOAD count distribution",
                  chart_bar("p_loadhist",
                            list(ptload.keys()),
                            [_n(v) for v in ptload.values()],
                            title="ELFs with N PT_LOAD segments"))
        + section("Total segment count distribution",
                  chart_bar("p_seghist",
                            list(seg.keys()),
                            [_n(v) for v in seg.values()],
                            title="ELFs with N total segments"))
        + section("Most-segmented binaries (top 100)",
                  table(["segments", "file"],
                        [[_fmt(x["count"]), f"<code>{_esc(x['path'])}</code>"]
                         for x in sv["top_segments"][:100]]))
    )


def build_dynamic(sv: dict) -> str:
    n = sv["n_files"]
    return (
        section("DT_* tag prevalence",
                kv_table(sv["dyn_tags"], key_label="DT_tag"))
        + section("DT_FLAGS bits",
                  kv_table(sv["dyn_flags"], key_label="DF_*"))
        + section("DT_FLAGS_1 bits",
                  kv_table(sv["dyn_flags_1"], key_label="DF_1_*"))
        + section("Hash table style", card_grid([
            kv_card("DT_GNU_HASH only",
                    _fmt(sv["files_with_dt_gnu_hash"]),
                    "modern style"),
            kv_card("Both DT_HASH + DT_GNU_HASH",
                    _fmt(sv["files_with_both_hash"]),
                    "legacy-compatible"),
            kv_card("DT_HASH only",
                    _fmt(sv["files_with_dt_hash"]),
                    "old style"),
            kv_card("neither hash",
                    _fmt(sv["files_with_neither_hash"]),
                    "dynamic but no hash table"),
        ]))
        + section("Symbol version tables", card_grid([
            kv_card("DT_VERNEED present", _fmt(sv["files_with_verneed"]),
                    f'{sv["files_with_verneed"]/n*100:.1f}% of files'),
            kv_card("DT_VERDEF present", _fmt(sv["files_with_verdef"]),
                    f'{sv["files_with_verdef"]/n*100:.1f}% of files'),
            kv_card("distinct Vernaux entries",
                    _fmt(len(sv["verneed_versions"])),
                    "GLIBC_2.x, ABI_1.0, …"),
        ]))
        + section("Most-referenced version strings (top 40)",
                  kv_table(sv["verneed_versions"],
                           key_label="version", limit=40))
        + section("Hardening", card_grid([
            kv_card("BIND_NOW", _fmt(sv["files_with_bind_now"]),
                    f'{sv["files_with_bind_now"]/n*100:.1f}%'),
            kv_card("TEXTREL", _fmt(sv["files_with_textrel"]),
                    "writable .text relocs"),
            kv_card("DT_RPATH", _fmt(sv["files_with_rpath"]),
                    "legacy search path"),
            kv_card("DT_RUNPATH", _fmt(sv["files_with_runpath"]),
                    "non-LD_LIBRARY_PATH search path"),
            kv_card("DT_RELR", _fmt(sv["files_with_relr"]),
                    "compact RELATIVE relocs"),
            kv_card("DT_JMPREL", _fmt(sv["files_with_jmprel"]),
                    "lazy-bind PLT relocations"),
        ]))
        + section("Loaders (PT_INTERP)",
                  kv_table(sv["interps"], key_label="interp path"))
    )


def build_relocations(sv: dict) -> str:
    n = sv["n_files"]
    parts = [
        section("Reloc type prevalence (top 50 of "
                f"{len(sv['reloc_types'])})",
                kv_table(sv["reloc_types"], key_label="reloc type",
                         limit=50)),
        section("Reloc categories", card_grid([
            kv_card("IFUNC reloc users",
                    _fmt(sv["files_with_ifunc_reloc"])),
            kv_card("COPY reloc users",
                    _fmt(sv["files_with_copy_reloc"]),
                    f'{sv["files_with_copy_reloc"]/n*100:.1f}%'),
            kv_card("TLS reloc users",
                    _fmt(sv["files_with_tls_reloc"]),
                    f'{sv["files_with_tls_reloc"]/n*100:.1f}%'),
            kv_card("no relocations",
                    _fmt(sv["files_no_relocations"]),
                    f'{sv["files_no_relocations"]/n*100:.1f}% of files'),
        ])),
    ]
    for arch, types in sorted(sv["reloc_types_per_arch"].items(),
                              key=lambda kv: -sum(_n(v) for v in kv[1].values())):
        if not types:
            continue
        parts.append(section(
            f"{arch}: reloc type distribution "
            f"({len(types)} types)",
            kv_table(types, key_label="reloc type", limit=40),
            anchor=f"arch-{arch}",
        ))
    parts.append(section(
        "Top relocations-per-binary (top 100)",
        table(["relocations", "file"],
              [[_fmt(x["count"]), f"<code>{_esc(x['path'])}</code>"]
               for x in sv["top_reloc"][:100]])
    ))
    return "".join(parts)


def build_symbols(sv: dict) -> str:
    return (
        section("Symbol binding (st_info >> 4)",
                chart_pie("s_bind", *top_n(sv["sym_binding"]))
                + kv_table(sv["sym_binding"], key_label="STB_"))
        + section("Symbol type (st_info & 0xf)",
                  chart_pie("s_type", *top_n(sv["sym_type"]))
                  + kv_table(sv["sym_type"], key_label="STT_"))
        + section("Symbol visibility (st_other)",
                  chart_pie("s_vis", *top_n(sv["sym_visibility"]))
                  + kv_table(sv["sym_visibility"], key_label="STV_"))
        + section("IFUNC / weak-undef summary", card_grid([
            kv_card("STT_GNU_IFUNC symbol users",
                    _fmt(sv["files_with_ifunc_sym"])),
            kv_card("DT_VERNEED files",
                    _fmt(sv["files_with_verneed"])),
            kv_card("DT_VERDEF files",
                    _fmt(sv["files_with_verdef"])),
        ]))
    )


def build_notes(sv: dict) -> str:
    return (
        section("ELF note types (.note.*)",
                kv_table(sv["note_types"], key_label="note type"))
        + section("GNU properties (NT_GNU_PROPERTY_TYPE_0)",
                  kv_table(sv["gnu_property"],
                           key_label="property type / value"))
        + section("Build-ID coverage", card_grid([
            kv_card("ELFs with .note.gnu.build-id",
                    _fmt(sv["files_with_build_id"]),
                    f'{sv["files_with_build_id"]/sv["n_files"]*100:.1f}% of files'),
        ]))
    )


def build_packages(sv: dict) -> str:
    pkg_files = sv["pkg_n_files"]
    pkg_relocs = sv["pkg_total_relocs"]
    top_files = sorted(pkg_files.items(), key=lambda kv: -_n(kv[1]))[:100]
    top_relocs = sorted(pkg_relocs.items(), key=lambda kv: -_n(kv[1]))[:100]
    return (
        section("Most ELF-heavy packages (top 100)",
                table(["ELF files", "package"],
                      [[_fmt(_n(v)), _esc(k)] for k, v in top_files]))
        + section("Most reloc-heavy packages (top 100)",
                  table(["relocations", "package"],
                        [[_fmt(_n(v)), _esc(k)] for k, v in top_relocs]))
        + section("Per-package summary", f"""
<p>The full corpus is split across <strong>{_fmt(len(pkg_files))}</strong>
packages. Median ELF files per package: <strong>{_median(pkg_files):.0f}</strong>;
99th percentile: <strong>{_pct(pkg_files, 99):.0f}</strong>.</p>
""")
    )


def build_needed(sv: dict) -> str:
    needed = sv["needed_libs"]
    hist = {str(k): v for k, v in sv["needed_count_histogram"].items()}
    return (
        section("Most-referenced DT_NEEDED libraries (top 50)",
                chart_bar("n_top", *top_n(needed, 25),
                          title="Top 25 NEEDED libs",
                          horizontal=True, height=520)
                + kv_table(needed, key_label="library", limit=50))
        + section("DT_NEEDED count per binary",
                  chart_bar("n_hist",
                            sorted(hist.keys(), key=lambda x: int(x)),
                            [_n(hist[k]) for k in sorted(hist.keys(),
                                                         key=lambda x: int(x))],
                            title="ELFs with N NEEDED entries"))
        + section("Most-NEEDED-heavy binaries (top 100)",
                  table(["NEEDED count", "file"],
                        [[_fmt(x["count"]), f"<code>{_esc(x['path'])}</code>"]
                         for x in sv["top_needed"][:100]]))
        + section("All distinct DT_NEEDED libraries", details(
            f"show all {_fmt(len(needed))} entries",
            kv_table(needed, key_label="library")
        ))
    )


# Friendly names for the survey-side anomaly kinds. The dict is small;
# unknown kinds fall back to their raw key.
ANOMALY_DESCRIPTIONS = {
    "ph_load_wx":
        "PT_LOAD segment is both writable and executable (W+X). "
        "Real hardening concern.",
    "ph_exec_stack":
        "PT_GNU_STACK is executable. Allows code execution on the "
        "stack — increasingly rare.",
    "ph_interp_after_load":
        "PT_INTERP appears after the first PT_LOAD. gabi requires "
        "PT_INTERP to precede the first loadable segment.",
    "ph_offset_vaddr_misaligned":
        "Program header has p_offset and p_vaddr that disagree "
        "modulo p_align. gabi requires "
        "p_offset ≡ p_vaddr (mod p_align).",
    "ph_phdr_not_in_load":
        "PT_PHDR present but its range is not contained in any "
        "PT_LOAD. The phdr table must be loaded into memory.",
    "dyn_textrel":
        "DT_TEXTREL present: relocations into a non-writable text "
        "segment, defeats RELRO.",
    "dyn_no_hash":
        "Dynamic ELF with neither DT_HASH nor DT_GNU_HASH. Mostly "
        "Guile .go bytecode files masquerading as ELF.",
    "dyn_empty":
        "PT_DYNAMIC present but DT_* table is empty (or only "
        "contains DT_NULL). Stripped or synthetic ELFs — common "
        "for /usr/lib/debug debuginfo and Guile .go.",
    "dyn_missing_mandatory":
        "Dynamic ELF missing one of the mandatory DT_* tags "
        "(DT_STRTAB / DT_SYMTAB / DT_STRSZ / DT_SYMENT). Each "
        "missing tag counts once, so the total exceeds the file "
        "count.",
    "arch_mismatch":
        "ELF's e_machine doesn't match x86_64 — cross-arch object "
        "files shipped in x86_64 packages (avr-libc, "
        "{i686,arm,riscv64}-elf-binutils, etc.).",
    "ehdr_unknown_machine":
        "e_machine value not in the standard EM_* enum.",
    "ehdr_nonzero_abiversion":
        "e_ident[EI_OSABI] is non-zero. gabi reserves this byte for "
        "OS-specific extensions; most ELFs leave it 0.",
}


def build_categories(survey: dict) -> str:
    cats = survey["category_counts"]
    n = survey["n_files"]
    order = ["loadable", "debuginfo", "relocatable", "cross_arch", "other"]
    descs = {
        "loadable": "Real loadable ELFs targeting x86_64 — "
            "executables and shared objects the dynamic loader is "
            "expected to handle. This is the loader-spec target; "
            "all the other site pages show data from this bucket.",
        "debuginfo": "Stripped debug-only ELFs under "
            "<code>/usr/lib/debug/</code> or with <code>.debug</code> "
            "/ <code>.dbg</code> suffix. PT_DYNAMIC is empty by "
            "construction.",
        "relocatable": "Unlinked object files (ET_REL). Mostly "
            "shipped in <code>-dev</code> packages; "
            "<code>avr-libc</code>, "
            "<code>{i686,arm,riscv64}-elf-binutils</code>, and "
            "kernel sources contribute the most.",
        "cross_arch": "ET_EXEC / ET_DYN files whose e_machine is "
            "not x86_64 — typically firmware images or "
            "cross-compiler runtimes shipped in x86_64 packages "
            "(qemu's vfat ROM, etc.).",
        "other": "Files we couldn't classify by architecture — "
            "EM_NONE (Guile .go bytecode wraps itself in an ELF "
            "container with e_machine=0), EM_PARISC core dumps, "
            "and a handful with bogus e_machine values.",
    }
    rows = []
    for c in order:
        bc = survey["by_category"].get(c, {})
        rows.append([
            _esc(c),
            descs.get(c, ""),
            _fmt(bc.get("n_files", 0)),
            f'{bc.get("n_files", 0)/n*100:.2f}%' if n else "—",
            _fmt(sum(bc.get("anomalies", {}).values())),
            _fmt(len(bc.get("anomalies", {}))),
        ])

    pie_labels = [c for c in order if cats.get(c)]
    pie_vals = [cats[c] for c in pie_labels]

    out = [section("Five-bucket classification", f"""
<p>Every ELF in the corpus is sorted into exactly one of five
categories. Other site pages render the <strong>loadable</strong>
bucket because that's the actual loader-spec target —
real dynamic-linker inputs without debuginfo / relocatable noise.</p>
<p>Total: <strong>{_fmt(n)}</strong> ELFs across
<strong>{len(cats)}</strong> categories.</p>
""" + chart_pie("c_pie", pie_labels, pie_vals,
                "ELFs per category") + table(
        ["category", "description", "files", "share",
         "anomaly hits", "anomaly kinds"], rows, sortable=False))]

    for c in order:
        bc = survey["by_category"].get(c, {})
        if not bc.get("n_files"):
            continue
        machines = bc.get("machine", {})
        types = bc.get("elf_type", {})
        body = f"""<p>{descs[c]}</p>
<p><strong>{_fmt(bc["n_files"])}</strong> files.</p>"""
        body += "<h3>e_type</h3>" + kv_table(types, key_label="ET_")
        body += ("<h3>e_machine (top 10)</h3>"
                 + kv_table(machines, key_label="EM_", limit=10))
        anoms = bc.get("anomalies", {})
        if anoms:
            body += "<h3>anomalies</h3>" + kv_table(
                anoms, key_label="kind")
        out.append(section(f"category: {c}", body, anchor=f"c-{c}"))
    return "".join(out)


def build_hardening(sv: dict) -> str:
    """Hardening + ABI features — loadable bucket only."""
    n = sv["n_files"]
    cet = sv.get("cet_adoption", {})
    cards = [
        kv_card("BIND_NOW", _fmt(sv["files_with_bind_now"]),
                f'{sv["files_with_bind_now"]/n*100:.1f}% — full RELRO'),
        kv_card("CET IBT", _fmt(cet.get("IBT", 0)),
                f'{cet.get("IBT", 0)/n*100:.2f}% — indirect-branch '
                f'tracking'),
        kv_card("CET SHSTK", _fmt(cet.get("SHSTK", 0)),
                f'{cet.get("SHSTK", 0)/n*100:.2f}% — shadow stack'),
        kv_card("TEXTREL", _fmt(sv["files_with_textrel"]),
                "writable .text relocs — bad"),
        kv_card("exec-stack", _fmt(sv["files_with_exec_stack"]),
                "PT_GNU_STACK is RWX"),
        kv_card("DT_RELR", _fmt(sv["files_with_relr"]),
                "compact RELATIVE relocs"),
    ]
    rp = sv.get("runpath_pattern_dist", {})
    gs = sv.get("gnu_stack_flags_dist", {})
    bid = sv.get("build_id_size_dist", {})
    bss = sv.get("bss_ratio_buckets", {})
    pla = sv.get("pt_load_align_dist", {})
    iso = sv.get("x86_64_isa_level_dist", {})
    f2 = sv.get("x86_feature2_dist", {})
    a64 = sv.get("aarch64_adoption", {})

    parts = [
        section("Hardening at a glance (loadable only)",
                card_grid(cards)),
        section("CET / GNU_PROPERTY_X86_FEATURE_1_AND",
                "<p>Indirect-branch tracking (IBT), shadow stack "
                "(SHSTK), and the LAM_U{48,57} markers. Distinct "
                "from <em>FEATURE_2</em> below, which describes "
                "register-class usage not security features.</p>"
                + kv_table(cet, key_label="feature")),
        section("x86-64 ISA level "
                "(GNU_PROPERTY_X86_ISA_1_NEEDED)",
                "<p>Minimum micro-architecture level the binary "
                "requires at load time. v2 = SSE4.2 + LAHF-SAHF, "
                "v3 = AVX2 + BMI, v4 = AVX-512.</p>"
                + chart_pie("h_iso", *top_n(iso))
                + kv_table(iso, key_label="ISA level")),
        section("x86 FEATURE_2 (used / needed)",
                "<p>From "
                "<code>GNU_PROPERTY_X86_FEATURE_2_USED</code> and "
                "<code>…_NEEDED</code>. Register-class fingerprint "
                "of the compiled code — orthogonal to CET.</p>"
                + kv_table(f2, key_label="feature", limit=30)),
        section("AArch64 hardening (BTI / PAC)",
                "<p>AArch64-only properties. Empty here because "
                "we sampled only x86_64.</p>"
                + (kv_table(a64, key_label="feature") if a64
                   else "<em>(none in this corpus)</em>")),
        section("PT_GNU_STACK permissions",
                kv_table(gs, key_label="flags")),
        section("DT_RUNPATH / DT_RPATH patterns",
                "<p><code>$ORIGIN</code> = relative to the binary "
                "(reproducible); <code>absolute</code> = hard-coded "
                "absolute path; <code>relative-bare</code> = "
                "non-<code>$ORIGIN</code> relative path (rare; "
                "loader resolves against cwd).</p>"
                + kv_table(rp, key_label="pattern")),
        section("Build-ID size distribution",
                kv_table(bid, key_label="size (bytes)")),
        section("PT_LOAD alignment", kv_table(pla, key_label="bytes")),
        section("BSS ratio (memsz-vs-filesz in writable PT_LOAD)",
                "<p>How much of the writable segment lives only in "
                "memory (zeroed BSS). Very high ratios "
                "(>0.9) typically indicate large uninitialised "
                "globals or large COMMON.</p>"
                + kv_table(bss, key_label="ratio bucket")),
        section("SONAME presence",
                f"<p><strong>{_fmt(sv.get('soname_count', 0))}</strong> "
                f"of {_fmt(n)} loadable ELFs declare DT_SONAME "
                f"({sv.get('soname_count', 0)/n*100:.1f}%).</p>"),
    ]
    vlm = sv.get("versioned_lib_max", [])
    if vlm:
        rows = [[_esc(x["lib"]), _esc(x["verset"]), _esc(x["version"])]
                for x in sorted(vlm,
                                key=lambda r: (r["lib"], r["verset"]))[:80]]
        parts.append(section(
            "Highest symbol version per (lib, verset) "
            f"(top 80 of {_fmt(len(vlm))})",
            "<p>The largest version any binary depends on for each "
            "(library, version-set) pair — the dependency-floor "
            "the corpus would require from each library.</p>"
            + table(["library", "verset", "max version"], rows)))
    return "".join(parts)


def build_anomalies(sv_all: dict, by_cat: dict) -> str:
    """Anomalies page renders ALL files (every category) and breaks
    each kind down by category. Sample files come from the all-bucket
    reservoir."""
    anoms = sv_all["anomalies"]
    files = sv_all["anomaly_files"]
    items = sorted(anoms.items(), key=lambda kv: -kv[1])
    cats = ["loadable", "debuginfo", "relocatable", "cross_arch", "other"]

    summary_rows = []
    for k, v in items:
        per_cat = {c: by_cat.get(c, {}).get("anomalies", {}).get(k, 0)
                   for c in cats}
        row = [_esc(k), _fmt(v)]
        row += [_fmt(per_cat[c]) if per_cat[c] else "—" for c in cats]
        row.append(f"{v/sv_all['n_files']*100:.2f}%")
        summary_rows.append(row)

    out = [section(
        "Survey anomaly summary (all categories)",
        table(["kind", "total"] + cats + ["share"], summary_rows)
    )]
    out.append(section("Per-kind drill-down", "<p>Sample files are "
                       "uniform-random and deterministic — "
                       "<code>blake2b(kind, path, idx)</code> drawn into "
                       "a fixed-size reservoir. Stable across re-runs.</p>"))
    for k, c in items:
        desc = ANOMALY_DESCRIPTIONS.get(k, "")
        body = (
            (f"<p>{_esc(desc)}</p>" if desc else "")
            + f"<p><strong>{_fmt(c)}</strong> ELFs match. "
            + (f"Showing first {min(len(files.get(k, [])), 50)} samples "
               f"(of {len(files.get(k, []))} stored, up to 200):</p>"
               if files.get(k) else "<p>No file samples stored.</p>")
            + sample_list(files.get(k, []), max_n=50)
        )
        out.append(section(k, body, anchor=f"a-{k}"))
    return "".join(out)


def build_elflint(el: dict) -> str:
    kinds = el["kinds"]
    hist = el["findings_per_file_histogram"]
    # bucket the long histogram
    bucketed: dict[str, int] = {}
    for k, v in hist.items():
        n = int(k)
        if n == 0:
            label = "0"
        elif n == 1:
            label = "1"
        elif n <= 5:
            label = "2-5"
        elif n <= 10:
            label = "6-10"
        elif n <= 50:
            label = "11-50"
        elif n <= 100:
            label = "51-100"
        else:
            label = ">100"
        bucketed[label] = bucketed.get(label, 0) + int(v)
    order = ["0", "1", "2-5", "6-10", "11-50", "51-100", ">100"]
    blabels = [l for l in order if l in bucketed]
    bvals = [bucketed[l] for l in blabels]

    out = [section("eu-elflint at a glance", card_grid([
        kv_card("clean files", _fmt(el["n_clean"]),
                f'{el["n_clean"]/el["n_files"]*100:.1f}%'),
        kv_card("dirty files", _fmt(el["n_dirty"]),
                f'{el["n_dirty"]/el["n_files"]*100:.1f}%'),
        kv_card("total findings", _fmt(el["n_total_findings"])),
        kv_card("distinct kinds", _fmt(el["n_distinct_kinds"]),
                "after message normalisation"),
    ])),
        section("Findings per ELF",
                chart_bar("e_hist", blabels, bvals,
                          title="ELFs grouped by # of findings",
                          height=280)),
    ]
    rows = []
    for k in kinds:
        rows.append([
            _fmt(k["count"]),
            f'<code>{_esc(k["kind"])}</code>',
            sample_list(k["samples"], max_n=10),
        ])
    out.append(section(
        f"All {len(kinds)} message templates (sorted by frequency)",
        table(["count", "template", "sample files"], rows)
    ))
    return "".join(out)


def _bucket_closure_hist(hist: dict) -> tuple[list[str], list[int]]:
    """Bucket the per-file closure size histogram into log-ish buckets."""
    buckets = [
        ("0", 0, 0),
        ("1", 1, 1),
        ("2-5", 2, 5),
        ("6-10", 6, 10),
        ("11-25", 11, 25),
        ("26-50", 26, 50),
        ("51-100", 51, 100),
        ("101-200", 101, 200),
        ("201-336", 201, 10_000),
    ]
    out_labels = [b[0] for b in buckets]
    out_counts = [0] * len(buckets)
    for k, v in hist.items():
        n = int(k)
        for i, (_, lo, hi) in enumerate(buckets):
            if lo <= n <= hi:
                out_counts[i] += int(v)
                break
    return out_labels, out_counts


def build_depgraph(g: dict, sv: dict) -> str:
    """Render the corpus-wide DT_NEEDED graph analysis page.

    Uses the slim summary keys in `corpus/dep_graph.json` only — the
    full `closures` / `consumers` dicts are too large to surface
    here, but the curated top-N lists already capture the head of
    every distribution."""
    soname_use = g.get("soname_use", {})

    n_files = g["n_files"]
    n_providers = g["n_providers"]
    n_consumers = g["n_consumers"]
    n_sonames = g["n_sonames"]
    n_conflicts = g["n_conflicts"]
    n_external = g["n_external"]
    n_cycles = g["n_cycles"]
    n_vmism = g["n_version_mismatches"]
    n_load = sv["n_files"]

    out = []
    out.append(
        '<p>SONAME → DT_NEEDED graph built from every loadable '
        'ELF in the corpus. Closures are computed by BFS over the '
        'path graph; when a NEEDED soname has multiple in-corpus '
        'providers, the alphabetically-first one is picked '
        '(deterministic but ambiguous — flagged below). External '
        'sonames are NEEDED entries with no in-corpus provider — '
        'almost all are private plugin libs living in subdirs '
        '(LibreOffice <code>libreoffice/program/</code>, Perl '
        '<code>core_perl/CORE/</code>, etc.) that ld.so finds via '
        'DT_RPATH/RUNPATH at runtime.</p>'
    )

    out.append(section("At a glance", card_grid([
        kv_card("nodes",          _fmt(n_files),
                f"{n_files/n_load*100:.1f}% of loadable bucket"),
        kv_card("providers",      _fmt(n_providers),
                "files with DT_SONAME"),
        kv_card("consumers",      _fmt(n_consumers),
                "files with ≥1 DT_NEEDED"),
        kv_card("distinct sonames", _fmt(n_sonames),
                "across providers + NEEDED"),
        kv_card("provider conflicts", _fmt(n_conflicts),
                ">1 provider for one SONAME"),
        kv_card("external sonames", _fmt(n_external),
                "NEEDED with no in-corpus provider"),
        kv_card("dep-graph cycles", _fmt(n_cycles),
                "non-trivial SCCs at soname level"),
        kv_card("versioned-symbol mismatches", _fmt(n_vmism),
                "NEEDED verset absent from every provider"),
    ])))

    # Closure size histogram
    labels, vals = _bucket_closure_hist(g["closure_size_histogram"])
    out.append(section(
        "Closure size distribution",
        '<p>Number of DSOs reachable from each consumer, '
        'including the transitive closure. The huge spike at '
        '<strong>1</strong> is libc-only consumers '
        '(tens of thousands of small CLIs and helpers).</p>' +
        chart_bar("g_csize", labels, vals,
                  title="ELFs grouped by closure size",
                  height=280)
    ))

    # Top in-degree
    top_in = g.get("top_in_degree", [])[:30]
    in_labels = [d["soname"] for d in top_in]
    in_vals = [d["in_degree"] for d in top_in]
    out.append(section(
        "Top 30 most-depended-on sonames",
        '<p>How many in-corpus consumers list each SONAME as a '
        'direct DT_NEEDED. <code>libc.musl-x86_64.so.1</code> '
        'dominates — every dynamic Alpine binary lists it.</p>' +
        chart_bar("g_in", in_labels, in_vals,
                  title="in-degree (#consumers)",
                  horizontal=True, height=540)
    ))

    # Top out-degree
    top_out = g.get("top_out_degree", [])[:30]
    rows = [[_fmt(d["out_degree"]),
             f'<code>{_esc(d["path"])}</code>']
            for d in top_out]
    out.append(section(
        "Top 30 most-NEEDED-heavy ELFs",
        '<p>Files with the largest direct DT_NEEDED lists. These '
        'are typically big test binaries or "everything-linked" '
        'service binaries.</p>' +
        table(["NEEDED", "file"], rows)
    ))

    # Biggest closures
    bc = g.get("biggest_closure", [])[:30]
    rows = [[_fmt(d["closure_size"]),
             _fmt(d["external"]),
             f'<code>{_esc(d["path"])}</code>']
            for d in bc]
    out.append(section(
        "Top 30 largest transitive closures",
        '<p>How many distinct DSOs a binary <em>transitively</em> '
        'pulls in (BFS via NEEDED, picking the first in-corpus '
        'provider per SONAME). The biggest closures are KDE-PIM '
        'and KDE-mail plugins.</p>' +
        table(["closure size", "external", "file"], rows)
    ))

    # Provider conflicts
    cfs = g.get("conflicts", [])[:50]
    rows = []
    for c in cfs:
        provs = c["providers"]
        head = provs[:3]
        more = (f' … and {len(provs) - 3:,} more'
                if len(provs) > 3 else '')
        plist = sample_list(head, max_n=3)
        rows.append([
            _fmt(c["n"]),
            f'<code>{_esc(c["soname"])}</code>',
            plist + (f"<p><em>{more}</em></p>" if more else ""),
        ])
    out.append(section(
        f"Provider conflicts (top 50 of {_fmt(n_conflicts)})",
        '<p>SONAMEs declared by more than one file in the corpus. '
        'A few real causes: (1) symlink + real file both get '
        'recorded as separate ELFs (most cases); (2) plugin '
        'systems where every backend ships with the same SONAME '
        '(<code>libsane.so.1</code> for sane-backends, '
        '<code>lib.so</code> for OpenJDK\u2019s JLI plugins); '
        '(3) parallel toolchain installs '
        '(<code>libcc1plugin</code>, .NET runtime/bootstrap).</p>'
        + table(["#providers", "soname", "providers (head)"], rows)
    ))

    # External sonames (NEEDED but unprovided), joined with use count
    ext = g.get("external", [])
    ext_with_use = sorted(
        ((s, soname_use.get(s, 0)) for s in ext),
        key=lambda kv: -kv[1],
    )
    rows = [[_fmt(n), f'<code>{_esc(s)}</code>']
            for s, n in ext_with_use[:40]]
    out.append(section(
        f"External sonames (top 40 of {_fmt(n_external)})",
        '<p>NEEDED entries that no in-corpus ELF advertises via '
        'DT_SONAME. Most are private plugin libs that ld.so finds '
        'via DT_RPATH/RUNPATH — e.g. LibreOffice ships dozens of '
        'unversioned <code>*lo.so</code> backends under '
        '<code>/usr/lib/libreoffice/program/</code>.</p>'
        + table(["#consumers", "soname"], rows)
    ))

    # Cycles
    cyc = g.get("cycles", [])
    if cyc:
        rows = []
        for sc in cyc[:30]:
            rows.append([
                _fmt(len(sc)),
                "<br>".join(f"<code>{_esc(s)}</code>" for s in sc[:8])
                + (f"<br><em>… +{len(sc)-8} more</em>"
                   if len(sc) > 8 else "")
            ])
        body = (
            '<p>Non-trivial SCCs in the SONAME-level NEEDED '
            'graph.</p>' + table(["size", "members"], rows)
        )
    else:
        body = (
            '<p><strong>None.</strong> The corpus-wide SONAME-level '
            'NEEDED graph is a DAG — no in-corpus library cycles '
            'through itself. This is the expected outcome for a '
            'well-curated distribution: ld.so can resolve every '
            'dependency in a single topological pass without '
            'cycle-breaking heuristics.</p>'
        )
    out.append(section("Dep-graph cycles", body))

    # Version mismatches
    vm = g.get("version_mismatches", [])
    if vm:
        rows = []
        for m in vm[:30]:
            rows.append([
                _fmt(len(m.get("requesters", []))),
                f'<code>{_esc(m["soname"])}</code>',
                f'<code>{_esc(m["verset"])}</code>',
                sample_list(m.get("requesters", []), max_n=5),
            ])
        body = (
            '<p>Cases where some consumer requests '
            '<code>(soname, verset)</code> but no in-corpus '
            'provider of that soname declares that verset. '
            'Skips external sonames (e.g. glibc-only sets that '
            'Alpine resolves at runtime by virtue of not '
            'linking against them).</p>'
            + table(["#requesters", "soname", "verset", "samples"],
                    rows)
        )
    else:
        body = (
            '<p><strong>None.</strong> For every '
            '<code>(soname, verset)</code> requested via '
            'DT_VERNEED, some in-corpus provider of that SONAME '
            'declares that verset via DT_VERDEF. The corpus is '
            'self-consistent on versioned-symbol presence (modulo '
            'external sonames, which by construction can\u2019t '
            'be checked here).</p>'
        )
    out.append(section("Versioned-symbol mismatches", body))

    return "".join(out)


def _median(d: dict) -> float:
    xs = sorted(_n(v) for v in d.values())
    if not xs:
        return 0.0
    m = len(xs) // 2
    if len(xs) % 2 == 0:
        return (xs[m - 1] + xs[m]) / 2
    return xs[m]


def _pct(d: dict, p: int) -> float:
    xs = sorted(_n(v) for v in d.values())
    if not xs:
        return 0.0
    i = max(0, min(len(xs) - 1, int(len(xs) * p / 100)))
    return xs[i]


# ---------- style + main -----------------------------------------------------


STYLE_CSS = """
* { box-sizing: border-box; }
body {
  font: 15px/1.5 system-ui, sans-serif;
  margin: 0; color: #1a2330;
  background: #f3f5f8;
}
header {
  background: #1e2a3a; color: #eef; padding: 12px 20px 8px;
}
header h1 { margin: 0 0 4px; font-size: 20px; font-weight: 500; }
header h1 a { color: #fff; text-decoration: none; }
header nav { font-size: 13px; }
header nav a {
  color: #c5d8e8; text-decoration: none;
  margin-right: 4px; padding: 1px 6px; border-radius: 3px;
}
header nav a:hover { background: #2c3e5a; color: #fff; }
header nav a.active { background: #3b6ea5; color: #fff; }
header .byline { margin: 6px 0 0; color: #8aa; font-size: 12px; }

main { max-width: 1200px; margin: 0 auto; padding: 16px 20px; }

section {
  background: #fff; border: 1px solid #d8dde6; border-radius: 4px;
  padding: 14px 18px; margin-bottom: 16px;
}
section h2 {
  margin: 0 0 12px; font-size: 17px; font-weight: 600;
  color: #2a3a55; border-bottom: 1px solid #eef; padding-bottom: 6px;
}
section h3 { font-size: 14px; color: #555; margin: 14px 0 6px; }

.grid {
  display: grid; gap: 10px;
  grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
}
.card {
  background: #f8fafd; border: 1px solid #e0e6ee;
  border-radius: 4px; padding: 10px 12px;
}
.card .num {
  font-size: 22px; font-weight: 600; color: #2c4d7a;
}
.card .lbl { color: #555; font-size: 13px; margin-top: 2px; }
.card .sub { color: #889; font-size: 11px; margin-top: 1px; }

table.data {
  border-collapse: collapse; width: 100%;
  font-size: 13px; margin: 6px 0;
}
table.data th, table.data td {
  text-align: left; padding: 5px 8px;
  border-bottom: 1px solid #eef;
  vertical-align: top;
}
table.data th {
  background: #f0f3f8; font-weight: 600; color: #334;
  position: sticky; top: 0;
}
table.data td:first-child { font-variant-numeric: tabular-nums; white-space: nowrap; }
table.data tr:hover td { background: #f6faff; }
table.data code { font-size: 12px; color: #224; }

.chart { width: 100%; margin: 8px 0; }
details { margin: 8px 0; }
details > summary {
  cursor: pointer; color: #36598a; font-size: 13px;
  padding: 4px 0;
}
details > summary:hover { color: #1a3a70; }

ul.paths {
  margin: 4px 0; padding-left: 18px; list-style: none;
  font-size: 12px;
}
ul.paths li { margin: 1px 0; }
ul.paths li::before { content: "• "; color: #aaa; }
ul.paths code { color: #234; word-break: break-all; }

footer {
  text-align: center; padding: 12px; color: #889;
  font-size: 12px;
}
footer code { color: #336; }

@media (max-width: 700px) {
  main { padding: 10px; }
  section { padding: 10px 12px; }
}
"""


def main() -> int:
    if not SURVEY.is_file():
        print(f"build_site: {SURVEY} not found", file=sys.stderr)
        return 2
    if not ELFLINT.is_file():
        print(f"build_site: {ELFLINT} not found", file=sys.stderr)
        return 2

    survey = json.loads(SURVEY.read_text())
    el = json.loads(ELFLINT.read_text())
    g: dict | None = None
    if DEPGRAPH.is_file():
        g = json.loads(DEPGRAPH.read_text())
    else:
        print(f"build_site: {DEPGRAPH} not found — "
              "depgraph page will be skipped", file=sys.stderr)
    # Most pages drill into the loadable bucket — the actual
    # loader-spec target. Anomalies/categories pages keep access to
    # `all` and `by_category` for cross-bucket summaries.
    sv = survey["by_category"]["loadable"]
    sv_all = survey["all"]
    by_cat = survey["by_category"]
    cats = survey["category_counts"]

    SITE.mkdir(exist_ok=True)
    (SITE / "style.css").write_text(STYLE_CSS)
    # The dep_graph.json holds large path-keyed dicts (closures,
    # consumers, verneed, …) that are useless in the bundled
    # `data.json`. Embed only the slim summary keys.
    g_slim = None
    if g is not None:
        slim_keys = (
            "n_files", "n_providers", "n_consumers", "n_sonames",
            "n_conflicts", "n_external", "n_cycles",
            "n_version_mismatches", "closure_size_histogram",
            "top_in_degree", "top_out_degree", "biggest_closure",
            "conflicts", "external", "cycles", "version_mismatches",
            "soname_use",
        )
        g_slim = {k: g[k] for k in slim_keys if k in g}
    (SITE / "data.json").write_text(json.dumps(
        {"survey": survey, "elflint": el,
         **({"dep_graph": g_slim} if g_slim is not None else {})},
        indent=2) + "\n")

    n_total = survey["n_files"]
    n_loadable = sv["n_files"]
    byline_global = (
        f'Alpine main + community · x86_64 · {_fmt(n_total)} ELFs · '
        f'{_fmt(n_loadable)} loadable · static survey + '
        f'eu-elflint 0.190 oracle'
    )
    byline_loadable = (
        f'Loadable bucket — {_fmt(n_loadable)} ELFs '
        f'({n_loadable/n_total*100:.1f}% of {_fmt(n_total)} total). '
        f'See <a href="categories.html">Categories</a> for other '
        f'buckets.'
    )

    pages = [
        ("index.html",       "Dashboard",
         build_dashboard(survey, el, sv), byline_global),
        ("categories.html",  "Categories",
         build_categories(survey), byline_global),
        ("header.html",      "ELF Header",
         build_header(sv), byline_loadable),
        ("program.html",     "Program Headers",
         build_program(sv), byline_loadable),
        ("dynamic.html",     "Dynamic",
         build_dynamic(sv), byline_loadable),
        ("relocations.html", "Relocations",
         build_relocations(sv), byline_loadable),
        ("symbols.html",     "Symbols",
         build_symbols(sv), byline_loadable),
        ("notes.html",       "Notes & GNU props",
         build_notes(sv), byline_loadable),
        ("hardening.html",   "Hardening & ABI",
         build_hardening(sv), byline_loadable),
        ("packages.html",    "Packages",
         build_packages(sv), byline_loadable),
        ("needed.html",      "NEEDED graph",
         build_needed(sv), byline_loadable),
    ]
    if g is not None:
        pages.append(
            ("depgraph.html", "Dep graph",
             build_depgraph(g, sv), byline_loadable)
        )
    pages.extend([
        ("anomalies.html",   "Survey anomalies",
         build_anomalies(sv_all, by_cat), byline_global),
        ("elflint.html",     "elflint findings",
         build_elflint(el), byline_global),
    ])
    for href, title, body, byline in pages:
        (SITE / href).write_text(page(title, href, body, byline=byline))
        print(f"wrote {SITE / href}", file=sys.stderr)

    print(f"site built in {SITE}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
